src/measure: Add missing include
Add missing include for the QString class.

Fixes the following build errors:

	src/measure.h:60:11: error: field ‘m_name’ has incomplete type ‘QString’
	   QString m_name;
	src/measure.h:64:11: error: field ‘m_unit’ has incomplete type ‘QString’
	   QString m_unit;
	src/measure.h:45:27: error: could not convert ‘""’ from ‘const char [1]’ to ‘const QString&’
		 const QString& unit = "", int channel = -1);

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>