CI/travis/before_install_lib.sh: use `--no-check-certificate` in wget
On Mac OS X the certificates seem outdated, and cannot be verified.

Error is:
```
ERROR: cannot verify downloads.sourceforge.net's certificate, issued by ‘CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to downloads.sourceforge.net insecurely, use `--no-check-certificate'.
```

Updating them seems a bit too much hassle on Mac OS X with brew, because
there doesn't seem to be a `ca-certificates` package/equivalent.
So ignore these errors.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>